### ISSUE TITLE
Error while fetching client token

### ISSUE THREAD

**Issue by Narbe26** [plaid/pattern#192]
Hello,

I have an error, why i can solve it ?

error while fetching client token { display_message: null,
documentation_url: 'https://plaid.com/docs/?ref=error#invalid-request-errors',
 error_code: 'MISSING_FIELDS',
error_message:
'the following required fields are missing: client_id, secret',
error_type: 'INVALID_REQUEST',
request_id: 'SkBNWLWxCZ8V3c5',
suggested_action: null }

Thanks

**Comment by Tarious1** [comment]
Retry please

**Comment by Tarious1** [comment]
Retry please .

**Comment by lindawoo-plaid** [comment]
@Narbe26 , Did you fill out the client_id and secret in the .env file?

**Comment by lindawoo-plaid** [comment]
@Narbe26, 
I am wondering whether you would be willing to speak with me regarding your experience with Plaid Pattern.  I am soliciting feedback so that we can improve this sample app. 
Thanks,
Linda Woo
