### ISSUE TITLE
Looking for feedback on Pattern sample app

### ISSUE THREAD

**Issue by lindawoo-plaid** [plaid/pattern#205]
Hi everyone,
I am looking for feedback from developers who have used the Pattern sample apps so that we can make improvements to them.  If you are willing to chat with me, please let me know.  
Thanks.

**Comment by lindawoo-plaid** [comment]
@mattmbrightside, @davvit, @ raghvenders,
Would you be willing to provide feedback on the Plaid Pattern sample apps?

**Comment by ottograjeda** [comment]
Hi . I'm willing to provide feedback on the initial setup/sandbox. LMK what is needed. Thx !

**Comment by ottograjeda** [comment]
Great - I will email you shortly !

**Comment by davvit** [comment]
Sure, i will email you if you still interested.

**Comment by lindawoo-plaid** [comment]
@davvit yes, please email me!  thanks!
