### ISSUE TITLE
.env for production

### ISSUE THREAD

**Issue by johndpope** [plaid/pattern#210]
https://github.com/plaid/pattern/blob/master/.env.template

this does not show PLAID_SECRET_PRODUCTION value - 
does it need it? 

and does the SDK reference this .env file? 

is it not shown as the code is deemed unworthy for production? I'm seeing errors with the socket saying the environment is in sandbox even though I'm using production client id + keys.

**Comment by phoenixy1** [comment]
correct, we don't provide this as the app isn't intended for usage in production
