### ISSUE TITLE
Dev Docs - Link update needed for 404 to LinkButton.tsx

### ISSUE THREAD

**Issue by jkusachi** [plaid/pattern#212]
I encountered an issue regarding Link Update Mode, so I consulted Plaid docs

This page in particular - https://plaid.com/docs/link/update-mode/, has an example pointing to `LinkButton.tsx`

Looking at PRs, I came across this one (https://github.com/plaid/pattern/pull/190/files), which renames `LinkButton.tsx` to `LaunchLink.tsx`

Just wanted to bring this up for awareness and update, thank you.

**Comment by phoenixy1** [comment]
thanks for the report! I have submitted a PR to fix this and it should be merged and deployed next week.
