### ISSUE TITLE
Use Gitpod / Workspaces for easy example deployment

### ISSUE THREAD

**Issue by RyKilleen** [plaid/pattern#219]
For someone on my environment, it's pretty difficult to get these examples running locally in `development` instead of `sandbox`.

I'm on Windows, which means to use `make` I need to use WSL. Then there's the challenge of setting up HTTPS for your local environment. I'm personally able to navigate a lot of these challenges, but there's an easier way: [gitpod.io](https://gitpod.io)

Gitpod allows you to open the repo, run webservers, and have them automatically proxied for the outside world. You can open the remote session in VS Code for easy editing, much like Gitgub Codespaces. It feels like the perfect solution for a complex example like this repository!

`Temporal.io` makes great use of this, you can see an example linked from their docs here: https://docs.temporal.io/docs/typescript/introduction

I made an attempt at modifying this repo as-is to run on Gitpod, but I think there's several levels of proxying here I don't fully understand with Docker.

**Comment by ghernandez-plaid** [comment]
Hi @RyKilleen, my name is Gilberto and I'm on the Developer Relations team here at Plaid. Hope all is well! I was wondering if you're actively building with Plaid at the moment? I'm conducting a bit of research to understand our dev community a bit more and thought we might connect if you were actively building with Plaid (or have built out a Plaid integration in the past). Hope to hear back! Thanks 🙏

**Comment by Athayde3586** [comment]
Yes I am it's just that I got stuck and it asked to use postman and from
there it got more difficult and harder to use

**Comment by RyKilleen** [comment]
Closing this as it's been descended upon by bots.
