### ISSUE TITLE
Cannot "Link an Item" (does nothing)

### ISSUE THREAD

**Issue by wickahead** [plaid/pattern#22]
Trying to get Plaid Pattern working (working thru Getting Started section on GitHub)...

(checking "make logs" doesn't show any errors)
localhost:3000 renders page. I am able to "Add a New User" (multiple times), but after doing so, and attempting to click on "Link an Item", nothing happens.

Possible cause... updating the .env with my Plaid API keys.
I found my client_id, dev and sandbox secrets and pasted them into the .env file. But I didn't know what to put in for the PLAID_PUBLIC_KEY.

Apologies if I shouldn't be posting here (vs. opening a support ticket).
Thanks,
Mark

**Comment by davidzhanghp** [comment]
@wickahead I am in the progress of making a pull request that will update plaid pattern to be more representative of some changes that went out recently. Will let you know when that is ready

**Comment by davidzhanghp** [comment]
@wickahead please take another look at Pattern after #23  was merged and let me know if it makes more sense now
