### ISSUE TITLE
transactions seem inverted.

### ISSUE THREAD

**Issue by johndpope** [plaid/pattern#220]
I raised an internal case - https://dashboard.plaid.com/support/case/398248
I'm seeing transactions flipped around when viewing them.

Here - $52.51 is represented as positive 
<img width="1182" alt="Screen Shot 2022-02-23 at 11 46 08 am" src="https://user-images.githubusercontent.com/289994/155244355-eab4bd49-36d3-45cc-8f65-114bddbfda53.png">
<img width="1175" alt="Screen Shot 2022-02-23 at 11 46 01 am" src="https://user-images.githubusercontent.com/289994/155244357-51e7e55d-89f1-476b-afea-08bb4945e546.png">

is there a simple fix? Perhaps just times * -1 ?

**Comment by Tarious1** [comment]
Can I see the complete page? All is not showing and why are their negative amounts
![image](https://user-images.githubusercontent.com/91292752/155257262-73de20c5-76b9-445c-83d2-037228f5a439.png)

**Comment by johndpope** [comment]
I attached complete page in the support ticket. Those are someones' personal transactions. 
I've been using pattern for ages - and used to it being how it is. But apparently - the transactions on other platforms / repos are inverted. I plugged in my secret / ids here - and they appear correctly in negative format. 
https://github.com/cmenon12/bank-account-to-sheets
the complete page is 
<img width="1256" alt="Screen Shot 2022-02-23 at 4 05 34 pm" src="https://user-images.githubusercontent.com/289994/155264518-5850f4cb-7efa-4e80-9d49-408443abd89f.png">

but even if I look a single transaction in database - it's reflecting the above + positive value as opposed to the "correct" negative value. If you have access to backend - you could possibly confirm with these transaction ids (all being positive)
<img width="372" alt="Screen Shot 2022-02-23 at 4 08 05 pm" src="https://user-images.githubusercontent.com/289994/155264713-975d45dd-2850-4773-bd92-1a139d228a93.png">

**Comment by johndpope** [comment]
this is kinda workaround multiplication 
https://github.com/johndpope/fin/blob/master/backend_go/routes/transactions/transactions.go#L142

I got around it by blanketing the amount * -1 / but not flat on why this is what it is for this repo. 
<img width="525" alt="Screen Shot 2022-02-23 at 4 13 52 pm" src="https://user-images.githubusercontent.com/289994/155265096-5ebea241-9635-404a-8e06-a0b74b6b8005.png">

**Comment by Tarious1** [comment]
thanks is everything correct now?

**Comment by johndpope** [comment]
is there a reason why it's backwards?

**Comment by Tarious1** [comment]
What was the reason?

**Comment by johndpope** [comment]
"As you can see in [our documentation](https://plaid.com/docs/api/products/#transactions-get-response-transactions-amount), Plaid's Transactions product will return positive values when money moves out of an account and negative values when money moves in. For example, debit card purchases are positive; direct deposits and refunds are negative. You will notice that this is the case with all of the transactions in the two screenshots you provided; the alternative backend presents all transactions with the opposite sign."

https://plaid.com/docs/api/products/#transactions-get-response-transactions-amount
