### ISSUE TITLE
Checking: getItemsByUser() function signature diff ....

### ISSUE THREAD

**Issue by pkreipke** [plaid/pattern#223]
Just checking....

The Client's `useItems` hook has a function `getItemsByUser()` [here](https://github.com/plaid/pattern/blob/d04440da39e38b1203a99852cc329ab3923cd045/client/src/services/items.tsx#L39) who's signature includes a `refresh` value but the implementation [here](https://github.com/plaid/pattern/blob/d04440da39e38b1203a99852cc329ab3923cd045/client/src/services/items.tsx#L74) doesn't.

Since I'm trying to understand the token update flow I thought I'd ask if that was an oversight or related in any way.

Thanks!

**Comment by phoenixy1** [comment]
Hmm -- I'm not the author of the code, but looking at it I suspect this was just a copy/paste error with the signature. In either case, it doesn't seem directly to impact the token update flow since it looks like it doesn't call a Plaid API endpoint, just Pattern's own user database.

**Comment by Lindasueo** [comment]
https://github.com/plaid/plaid-openapi/pulls

**Comment by pkreipke** [comment]
Hi @Lindasueo, I'm not sure what you're telling me :-) - I don't see any actual code in the either open pull requests.

Are you asking for me to offer a fix? I'm afraid I don't know what the fix should be: I'm asking whether the extra param is not needed, or the implementation is missing something.

Thanks!

**Comment by Tarious1** [comment]
> Just checking....
> 
> The Client's `useItems` hook has a function `getItemsByUser()` [here](https://github.com/plaid/pattern/blob/d04440da39e38b1203a99852cc329ab3923cd045/client/src/services/items.tsx#L39) who's signature includes a `refresh` value but the implementation [here](https://github.com/plaid/pattern/blob/d04440da39e38b1203a99852cc329ab3923cd045/client/src/services/items.tsx#L74) doesn't.
> 
> Since I'm trying to understand the token update flow I thought I'd ask if that was an oversight or related in any way.
> 
> Thanks!

It's possible.  I had trouble with the pattern when opening the account. I have a team.  My account was open last year but I currently have no access to my funds.

**Comment by phoenixy1** [comment]
@lindawoo-plaid when you get a chance, can you take a look at this and fix if necessary?

**Comment by Tarious1** [comment]
May I have my notice I'd and claim number please
