### ISSUE TITLE
plaid product - need guidance / example of transactions_refresh

### ISSUE THREAD

**Issue by johndpope** [plaid/pattern#224]
<Endpoint
        endpoint="transactions"
        name="Transactions"
        categories={transactionsCategories}
        schema="/transactions/get/"
        description="Retrieve transactions for credit and depository accounts."
        transformData={transformTransactionsData}
      />

Need guidance on usage here within plaid pattern example / how is it possible to set this?

 <Endpoint
        endpoint="transactions"
        name="Transactions"
        categories={transactionsCategories}
        schema="/transactions/refresh/"
        description="Retrieve transactions for credit and depository accounts."
        transformData={transformTransactionsData}
      />

test.js
```javascript

import axios from 'axios';
let params = {
    "client_id": "",
    "secret": "",
    "access_token": ""
  };
axios.post(`https://production.plaid.com/transactions/refresh`, params)
.then((response) =>{
console.log("response:",response.data);
})
```
```javascript

  data: {
      display_message: null,
      documentation_url: 'https://plaid.com/docs/?ref=error#invalid-input-errors',
      error_code: 'INVALID_PRODUCT',
      error_message: 'client is not authorized to access the following products: ["transactions_refresh"]',
      error_type: 'INVALID_INPUT',
      request_id: 'nqVGD4RqmDzgzP8',
      suggested_action: null
    }

```

**Comment by johndpope** [comment]
https://github.com/plaid/pattern/blob/cb35de078515ac61da11c4eead9ad15a2ecdf7f7/server/routes/linkTokens.js#L29

maybe just add here??

**Comment by phoenixy1** [comment]
`/transactions/refresh` is only available for customers on monthly minimum contract plans (it is not available via pay-as-you-go plans) and is billed per call. Because of this, we recommend you contact your account manager for guidance on how to use this endpoint in a cost-effective way that is best for your use case. If you are not on a $500/month minimum contract plan, you will need to upgrade to one to use the endpoint.

**Comment by johndpope** [comment]
thank you Alex

**Comment by Tarious1** [comment]
Is it possible for me to get live or virtual assistant. I am experiencing difficult as well complicated.
