### ISSUE TITLE
plaid product - need guidance / example of tranfer

### ISSUE THREAD

**Issue by Bakhodir98** [plaid/pattern#246]
Added transfer product to .env file
{
"display_message":null,
"documentation_url":"https://plaid.com/docs/?ref=error#invalid-input-errors",
"error_code":"INVALID_PRODUCT",
"error_message":"client is not authorized to access the following products: [\"transfer\"]",
"error_type":"INVALID_INPUT",
"request_id":"bTmjHtEoYBmcXlS"
}

**Comment by phoenixy1** [comment]
Per the Transfer docs @ https://plaid.com/docs/transfer/ -- "Both Transfer and Transfer UI are currently in closed beta and approval is required to participate. They are only available to senders and recipients based in the United States. If you're interested in learning more about either product and potentially participating in the beta program, please reach out to your Plaid point of contact." If you are getting this error, you are have not joined the closed beta.
