### ISSUE TITLE
handleTransactionsWebhook.js missing case in switch statement

### ISSUE THREAD

**Issue by emagaram** [plaid/pattern#247]
Hi, I believe the switch statement in handleTransactionsWebhook.js should include "TRANSACTIONS_REMOVED". Thanks!

**Comment by phoenixy1** [comment]
@emagaram thanks for the report! I believe the current switch statement is correct -- listening for the `SYNC_UPDATES_AVAILABLE` webhook effectively replaces the need to listen for `TRANSACTIONS_REMOVED`, as any removed transactions will be reported via `SYNC_UPDATES_AVAILABLE`.

**Comment by emagaram** [comment]
That makes sense, but won't it log "unhandled webhook type received"?

**Comment by phoenixy1** [comment]
@emagaram hmm -- yes, I suppose it will!
