### ISSUE TITLE
500 Server Error

### ISSUE THREAD

**Issue by worked** [plaid/pattern#298]
Cloned and running locally. I can create a user, but when I click the Add a Bank button, it throws a 500 server error. I noticed that someone else had this issue prior, but was able to resolve by blowing their local away and recloning. I've done this, but still no joy.

https://github.com/plaid/pattern/issues/258

**Comment by worked** [comment]
![Screenshot 2024-02-21 at 2 17 07 PM](https://github.com/plaid/pattern/assets/266669/0cdc0156-4ce9-4154-907f-cedac8359142)

**Comment by phoenixy1** [comment]
@worked thanks for the report! It appears that the cause is that last week ngrok stopped supporting the version of the ngrok agent used by pattern -- my next step is to look into upgrading it.
