### ISSUE TITLE
How can I trigger a new Transaction?

### ISSUE THREAD

**Issue by CodyBontecou** [plaid/pattern#307]
I'd like to test the webhook that occurs when a new transaction is made. I'm curious what steps I should take to enable that.

**Comment by phoenixy1** [comment]
I'd recommend using the `user_transactions_dynamic` Sandbox user, then calling `/transactions/refresh`. More info here:  https://plaid.com/docs/transactions/#testing-transactions-in-sandbox

**Comment by CodyBontecou** [comment]
Yup, that works perfectly. Thank you
