### ISSUE TITLE
Install and Run locally

### ISSUE THREAD

**Issue by raghvenders** [plaid/pattern#77]
As I run the plaid pattern (end-end integration) locally (macOS), I could see the application getting launched in http://localhost:3000. When I add a user, I am able to see the user is getting listed. However, I am not able to see Link an Item button except the Remove user button.
![Screen Shot 2021-06-15 at 11 06 14 AM](https://user-images.githubusercontent.com/9973300/122086944-d1635280-cdc9-11eb-9e72-6a0e07f29666.png)

Please do check if any more steps or config to be included in the README.md > Getting Started.

**Comment by lindawoo-plaid** [comment]
Hi. Sorry about this.  You need to go to your [dashboard]( https://dashboard.plaid.com/team/api ) and configure your Oauth redirect URI to `http://localhost/3000/oauth-link`

I will update the readme to reflect this...

**Comment by raghvenders** [comment]
Thanks. For the Banks, sandbox login is not working - user_good/pass_good?

**Comment by lindawoo-plaid** [comment]
yes, these credentials should work in sandbox.  what error are you getting?  make sure the PLAID_ENV is set to `sandbox` in your .env file.
